#!/usr/bin/env bash
# Re-snapshot the secforms schema from the live sec-postgres container.
# Updates: reference/schema.sql (DDL dump) + a one-line table inventory comment in reference/schema.md.
# Read-only; runs as sec_admin via docker exec.

set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCHEMA_SQL="${SKILL_DIR}/reference/schema.sql"

CONTAINER="${SEC_POSTGRES_CONTAINER:-sec-postgres}"
DB="${PG_DB:-secforms}"
USER="${PG_SUPERUSER:-sec_admin}"

if ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER}$"; then
  echo "Container '${CONTAINER}' is not running." >&2
  exit 1
fi

ts="$(date -u +%FT%TZ)"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

echo "Dumping schema (DDL only) from ${CONTAINER}:${DB} ..." >&2
docker exec -i "${CONTAINER}" pg_dump \
  -U "${USER}" -d "${DB}" \
  --schema-only --schema=public --no-owner --no-acl \
  > "${tmp}"

{
  echo "-- Auto-generated by scripts/refresh-schema.sh on ${ts}"
  echo "-- Do not edit by hand. Source: pg_dump --schema-only of database '${DB}'."
  echo ""
  cat "${tmp}"
} > "${SCHEMA_SQL}"

table_count=$(docker exec -i "${CONTAINER}" psql -U "${USER}" -d "${DB}" -tAc \
  "SELECT count(*) FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE'")
fk_count=$(docker exec -i "${CONTAINER}" psql -U "${USER}" -d "${DB}" -tAc \
  "SELECT count(*) FROM pg_constraint WHERE contype='f' AND connamespace='public'::regnamespace")
form_count=$(docker exec -i "${CONTAINER}" psql -U "${USER}" -d "${DB}" -tAc \
  "SELECT count(*) FROM information_schema.tables WHERE table_schema='public' AND table_name LIKE 'form\\_%' ESCAPE '\\'")

echo "Snapshot: ${ts}  |  tables=${table_count}  |  fks=${fk_count}  |  form_*=${form_count}" >&2

# Best-effort: bump the snapshot line in reference/schema.md
sed -i "s|^Last snapshot:.*|Last snapshot: ${ts} — ${table_count} public tables, ${fk_count} foreign keys, no public enums.|" \
  "${SKILL_DIR}/reference/schema.md" 2>/dev/null || true

echo "Done. ${SCHEMA_SQL} updated." >&2
