-- Auto-generated by scripts/refresh-schema.sh on 2026-05-22T15:33:21Z
-- Do not edit by hand. Source: pg_dump --schema-only of database 'secforms'.

--
-- PostgreSQL database dump
--

\restrict cWBmGdN6dzAZMmoGX8TFCqR9sCfZXL7ICILT7hlpKS93HKT1CkisHFWTKwe71i2

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: enrich_company_v2(jsonb); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.enrich_company_v2(p jsonb) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
  v_cik text := p->>'company_cik';
BEGIN
  IF v_cik IS NULL THEN
    RAISE EXCEPTION 'enrich_company_v2: company_cik required';
  END IF;

  -- 1. company row (upsert in case of re-enrichment)
  INSERT INTO companies(
    company_cik, name, ticker, exchanges, former_names,
    sic, sic_description, state_of_incorp, address, website,
    investor_website, fiscal_year_end, entity_type, filer_category
  )
  VALUES (
    v_cik,
    p->>'name',
    p->>'ticker',
    COALESCE(p->'exchanges', '[]'::jsonb),
    COALESCE(p->'former_names', '[]'::jsonb),
    p->>'sic',
    p->>'sic_description',
    p->>'state_of_incorp',
    p->>'address',
    p->>'website',
    p->>'investor_website',
    p->>'fiscal_year_end',
    p->>'entity_type',
    p->>'filer_category'
  )
  ON CONFLICT (company_cik) DO UPDATE SET
    name              = EXCLUDED.name,
    ticker            = EXCLUDED.ticker,
    exchanges         = EXCLUDED.exchanges,
    former_names      = EXCLUDED.former_names,
    sic               = EXCLUDED.sic,
    sic_description   = EXCLUDED.sic_description,
    state_of_incorp   = EXCLUDED.state_of_incorp,
    address           = EXCLUDED.address,
    website           = EXCLUDED.website,
    investor_website  = EXCLUDED.investor_website,
    fiscal_year_end   = EXCLUDED.fiscal_year_end,
    entity_type       = EXCLUDED.entity_type,
    filer_category    = EXCLUDED.filer_category;

  -- 2. bulk-insert filings (n8n applies SCRAPE_LIST + 3yr filter before sending)
  INSERT INTO company_filings(company_cik, accession, form, filing_date, items)
  SELECT
    v_cik,
    f.accession,
    f.form,
    f.filing_date,
    f.items
  FROM jsonb_to_recordset(COALESCE(p->'filings', '[]'::jsonb))
    AS f(accession text, form text, filing_date date, items text)
  WHERE f.accession IS NOT NULL AND f.filing_date IS NOT NULL
  ON CONFLICT (company_cik, accession) DO NOTHING;

  -- 3. flip enriched flag
  UPDATE cik_list SET enriched = TRUE WHERE cik = v_cik;
END;
$$;


--
-- Name: enrich_entity(jsonb, text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.enrich_entity(p jsonb, kind text) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
BEGIN
  IF kind = 'company' THEN
    PERFORM enrich_company_v2(p);
  ELSIF kind = 'person' THEN
    PERFORM enrich_person_v2(p);
  ELSE
    RAISE EXCEPTION 'enrich_entity: kind must be "company" or "person", got %', kind;
  END IF;
END;
$$;


--
-- Name: enrich_person_v2(jsonb); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.enrich_person_v2(p jsonb) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
  v_cik text := p->>'person_cik';
BEGIN
  IF v_cik IS NULL THEN
    RAISE EXCEPTION 'enrich_person_v2: person_cik required';
  END IF;

  -- 1. person row (upsert)
  INSERT INTO people(person_cik, canonical_name, former_names, address, entity_type)
  VALUES (
    v_cik,
    p->>'canonical_name',
    COALESCE(p->'former_names', '[]'::jsonb),
    p->>'address',
    p->>'entity_type'
  )
  ON CONFLICT (person_cik) DO UPDATE SET
    canonical_name = EXCLUDED.canonical_name,
    former_names   = EXCLUDED.former_names,
    address        = EXCLUDED.address,
    entity_type    = EXCLUDED.entity_type;

  -- 2. bulk-insert filings
  INSERT INTO people_filings(person_cik, accession, form, filing_date)
  SELECT
    v_cik,
    f.accession,
    f.form,
    f.filing_date
  FROM jsonb_to_recordset(COALESCE(p->'filings', '[]'::jsonb))
    AS f(accession text, form text, filing_date date)
  WHERE f.accession IS NOT NULL AND f.filing_date IS NOT NULL
  ON CONFLICT (person_cik, accession) DO NOTHING;

  -- 3. flip enriched flag
  UPDATE cik_list SET enriched = TRUE WHERE cik = v_cik;
END;
$$;


--
-- Name: import_entity_filings(text, jsonb); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.import_entity_filings(p_cik text, p_sub jsonb) RETURNS integer
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
  v_is_company boolean;
  v_is_person  boolean;
  v_scrape     text[];
  v_recent     jsonb := p_sub->'filings'->'recent';
  v_n          int;
  v_inserted   int := 0;
BEGIN
  IF v_recent IS NULL OR jsonb_typeof(v_recent->'accessionNumber') <> 'array' THEN
    RETURN 0;
  END IF;

  SELECT EXISTS (SELECT 1 FROM companies WHERE company_cik = p_cik) INTO v_is_company;
  SELECT EXISTS (SELECT 1 FROM people    WHERE person_cik  = p_cik) INTO v_is_person;
  IF NOT (v_is_company OR v_is_person) THEN
    RETURN 0;
  END IF;

  SELECT array_agg(form) INTO v_scrape FROM forms;
  v_n := jsonb_array_length(v_recent->'accessionNumber');
  IF v_n = 0 THEN RETURN 0; END IF;

  WITH zipped AS (
    SELECT
      (v_recent->'accessionNumber'->>i)::text AS accession,
      (v_recent->'form'->>i)::text             AS form,
      (v_recent->'filingDate'->>i)::text       AS filing_date,
      COALESCE(v_recent->'items'->>i,'')::text AS items
    FROM generate_series(0, v_n - 1) AS i
  ),
  filtered AS (
    SELECT accession, form, filing_date::date AS filing_date, NULLIF(items,'') AS items
    FROM zipped
    WHERE accession IS NOT NULL AND accession <> ''
      AND form = ANY(v_scrape)
      AND filing_date <> ''
      AND filing_date::date >= current_date - interval '3 years'
  ),
  ins_c AS (
    INSERT INTO company_filings (company_cik, accession, form, filing_date, items)
    SELECT p_cik, accession, form, filing_date, items FROM filtered
    WHERE v_is_company
    ON CONFLICT (company_cik, accession) DO NOTHING
    RETURNING 1
  ),
  ins_p AS (
    INSERT INTO people_filings (person_cik, accession, form, filing_date)
    SELECT p_cik, accession, form, filing_date FROM filtered
    WHERE v_is_person
    ON CONFLICT (person_cik, accession) DO NOTHING
    RETURNING 1
  )
  SELECT (SELECT count(*) FROM ins_c) + (SELECT count(*) FROM ins_p) INTO v_inserted;

  RETURN v_inserted;
END;
$$;


--
-- Name: ingest_signal(jsonb); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.ingest_signal(p jsonb) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $_$
DECLARE
  v_accession  text := p->>'accession';
  v_form_type  text := p->>'form_type';
  v_table      text;
  v_payload    jsonb;
  v_cik        record;
BEGIN
  IF v_accession IS NULL OR v_form_type IS NULL THEN
    RAISE EXCEPTION 'ingest_signal: accession and form_type required';
  END IF;

  INSERT INTO signals(accession, form_type, date_added)
  VALUES (v_accession, v_form_type, now())
  ON CONFLICT (accession) DO NOTHING;

  v_table := CASE v_form_type
    WHEN '3'        THEN 'form_3'
    WHEN '3/A'      THEN 'form_3'
    WHEN '4'        THEN 'form_4'
    WHEN '4/A'      THEN 'form_4_a'
    WHEN '5'        THEN 'form_5'
    WHEN '5/A'      THEN 'form_5'
    WHEN 'D'        THEN 'form_d_a'
    WHEN 'D/A'      THEN 'form_d_a'
    WHEN 'C'        THEN 'form_c'
    WHEN 'C/A'      THEN 'form_c_a'
    WHEN '8-K'      THEN 'form_8_k'
    WHEN '10-Q'     THEN 'form_10_q'
    WHEN 'S-1'      THEN 'form_s_1'
    WHEN 'S-1/A'    THEN 'form_s_1_a'
    WHEN 'S-3'      THEN 'form_s_3'
    WHEN 'DEF 14A'  THEN 'form_def_14a'
    WHEN '13F-HR'   THEN 'form_13f_hr'
    WHEN '13F-NT'   THEN 'form_13f_nt'
    WHEN '144'      THEN 'form_144'
    WHEN '144/A'    THEN 'form_144_a'
    WHEN 'N-CEN'    THEN 'form_n_cen'
    WHEN 'N-PX'     THEN 'form_n_px'
    WHEN 'N-PORT'   THEN 'form_n_port'
    WHEN 'N-14'     THEN 'form_n_14'
    WHEN '40-APP'   THEN 'form_40_app'
    WHEN '425'      THEN 'form_425'
    WHEN 'FWP'      THEN 'form_fwp'
    WHEN '424B5'    THEN 'form_424b5'
    WHEN 'SC 13D'   THEN 'form_sc_13d'
    WHEN 'SC 13G'   THEN 'form_sc_13g'
    ELSE NULL
  END;

  IF v_table IS NULL THEN
    RAISE EXCEPTION 'ingest_signal: unknown form_type %', v_form_type;
  END IF;

  v_payload := p - 'ciks';

  EXECUTE format(
    'INSERT INTO %1$I SELECT (jsonb_populate_record(NULL::%1$I, $1)).* ON CONFLICT (accession) DO NOTHING',
    v_table
  ) USING v_payload;

  FOR v_cik IN
    SELECT DISTINCT cik FROM jsonb_to_recordset(p->'ciks') AS x(cik text, role text)
    WHERE cik IS NOT NULL
  LOOP
    INSERT INTO cik_list(cik, date_added, enriched)
    VALUES (v_cik.cik, now(), FALSE)
    ON CONFLICT (cik) DO NOTHING;
  END LOOP;

  INSERT INTO signal_ciks(accession, cik, cik_role)
  SELECT v_accession, x.cik, x.role
  FROM jsonb_to_recordset(p->'ciks') AS x(cik text, role text)
  WHERE x.cik IS NOT NULL AND x.role IS NOT NULL
  ON CONFLICT (accession, cik, cik_role) DO NOTHING;
END;
$_$;


--
-- Name: ingest_signals_bulk(jsonb); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.ingest_signals_bulk(p jsonb) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
DECLARE
  v_item    jsonb;
  v_ok      int    := 0;
  v_err     int    := 0;
  v_errors  jsonb  := '[]'::jsonb;
BEGIN
  IF jsonb_typeof(p) <> 'array' THEN
    RAISE EXCEPTION 'ingest_signals_bulk: p must be a jsonb array, got %', jsonb_typeof(p);
  END IF;

  FOR v_item IN SELECT jsonb_array_elements(p) LOOP
    BEGIN
      PERFORM ingest_signal(v_item);
      v_ok := v_ok + 1;
    EXCEPTION WHEN OTHERS THEN
      v_err := v_err + 1;
      v_errors := v_errors || jsonb_build_object(
        'accession', v_item->>'accession',
        'form_type', v_item->>'form_type',
        'sqlstate',  SQLSTATE,
        'error',     SQLERRM
      );
    END;
  END LOOP;

  RETURN jsonb_build_object(
    'ok',     v_ok,
    'err',    v_err,
    'errors', v_errors
  );
END;
$$;


--
-- Name: refresh_forms_counts(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.refresh_forms_counts() RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public', 'pg_temp'
    AS $$
BEGIN
  -- filings_count = signals per form_type
  UPDATE forms f SET filings_count = COALESCE(s.cnt, 0)
  FROM (
    SELECT form_type, count(*) AS cnt FROM signals GROUP BY form_type
  ) s
  WHERE f.form = s.form_type;

  -- form_types not in signals → 0
  UPDATE forms f SET filings_count = 0
  WHERE NOT EXISTS (SELECT 1 FROM signals s WHERE s.form_type = f.form);

  -- companies_count = distinct company_cik linked to any signal of this form_type
  UPDATE forms f SET companies_count = COALESCE(s.cnt, 0)
  FROM (
    SELECT s.form_type, count(DISTINCT c.company_cik) AS cnt
    FROM signals s
    JOIN signal_ciks sc ON sc.accession = s.accession
    JOIN companies c    ON c.company_cik = sc.cik
    GROUP BY s.form_type
  ) s
  WHERE f.form = s.form_type;

  UPDATE forms f SET companies_count = 0
  WHERE NOT EXISTS (
    SELECT 1 FROM signals s
    JOIN signal_ciks sc ON sc.accession = s.accession
    JOIN companies c    ON c.company_cik = sc.cik
    WHERE s.form_type = f.form
  );
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cik_list; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cik_list (
    cik text NOT NULL,
    date_added timestamp with time zone DEFAULT now() NOT NULL,
    enriched boolean DEFAULT false NOT NULL
);


--
-- Name: companies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.companies (
    company_cik text NOT NULL,
    name text NOT NULL,
    ticker text,
    exchanges jsonb,
    former_names jsonb,
    sic text,
    sic_description text,
    state_of_incorp text,
    address text,
    website text,
    investor_website text,
    fiscal_year_end text,
    entity_type text NOT NULL,
    filer_category text,
    date_added timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: company_filings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_filings (
    company_cik text NOT NULL,
    accession text NOT NULL,
    form text NOT NULL,
    filing_date date NOT NULL,
    items text,
    date_added timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: form_10_q; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_10_q (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    body_text_head text NOT NULL,
    document_title text
);


--
-- Name: form_13f_hr; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_13f_hr (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    company_cik text NOT NULL,
    company_name text NOT NULL,
    report_type text NOT NULL,
    period_of_report date NOT NULL,
    table_entry_total bigint,
    table_value_total bigint
);


--
-- Name: form_13f_nt; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_13f_nt (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    company_cik text NOT NULL,
    company_name text NOT NULL,
    report_type text NOT NULL,
    period_of_report date NOT NULL,
    table_entry_total jsonb,
    table_value_total jsonb
);


--
-- Name: form_144; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_144 (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    issuer_name text NOT NULL,
    company_name text NOT NULL,
    issuer_cik text NOT NULL,
    company_cik text NOT NULL,
    seller_name text,
    person_name text,
    relationships jsonb,
    security_class_title text NOT NULL,
    broker_name text,
    total_shares bigint,
    agg_market_value numeric,
    approx_sale_date date,
    shares_outstanding bigint,
    exchange_name text,
    nature_of_acquisition text,
    date_of_acquisition date,
    acquired_from text,
    amount_acquired bigint,
    is_gift boolean
);


--
-- Name: form_144_a; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_144_a (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    issuer_name text NOT NULL,
    company_name text NOT NULL,
    issuer_cik text NOT NULL,
    company_cik text NOT NULL,
    seller_name text,
    person_name text,
    relationships jsonb,
    security_class_title text NOT NULL,
    broker_name text,
    total_shares bigint,
    agg_market_value numeric,
    approx_sale_date date,
    shares_outstanding bigint,
    exchange_name text,
    nature_of_acquisition text,
    date_of_acquisition date,
    acquired_from text,
    amount_acquired bigint,
    is_gift boolean
);


--
-- Name: form_3; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_3 (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    period_of_report date NOT NULL,
    not_subject_to_section16 jsonb,
    issuer_cik text NOT NULL,
    issuer_name text NOT NULL,
    issuer_trading_symbol text,
    company_cik text NOT NULL,
    company_name text NOT NULL,
    reporting_owners jsonb NOT NULL,
    person_cik text NOT NULL,
    person_name text NOT NULL,
    is_officer boolean,
    is_director boolean,
    is_ten_pct boolean,
    officer_title text,
    transactions jsonb NOT NULL,
    sale_count bigint NOT NULL,
    total_sale_usd numeric NOT NULL
);


--
-- Name: form_4; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_4 (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    period_of_report date NOT NULL,
    not_subject_to_section16 boolean,
    issuer_cik text NOT NULL,
    issuer_name text NOT NULL,
    issuer_trading_symbol text NOT NULL,
    company_cik text NOT NULL,
    company_name text NOT NULL,
    reporting_owners jsonb NOT NULL,
    person_cik text NOT NULL,
    person_name text NOT NULL,
    is_officer boolean,
    is_director boolean,
    is_ten_pct boolean,
    officer_title jsonb,
    transactions jsonb NOT NULL,
    sale_count bigint NOT NULL,
    total_sale_usd numeric NOT NULL
);


--
-- Name: form_40_app; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_40_app (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    body_text_head text NOT NULL,
    document_title text
);


--
-- Name: form_424b5; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_424b5 (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    body_text_head text NOT NULL,
    document_title text
);


--
-- Name: form_425; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_425 (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    body_text_head text NOT NULL,
    document_title text
);


--
-- Name: form_4_a; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_4_a (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    period_of_report date NOT NULL,
    not_subject_to_section16 boolean,
    issuer_cik text NOT NULL,
    issuer_name text NOT NULL,
    issuer_trading_symbol text NOT NULL,
    company_cik text NOT NULL,
    company_name text NOT NULL,
    reporting_owners jsonb NOT NULL,
    person_cik text NOT NULL,
    person_name text NOT NULL,
    is_officer boolean,
    is_director boolean,
    is_ten_pct boolean,
    officer_title text,
    transactions jsonb NOT NULL,
    sale_count bigint NOT NULL,
    total_sale_usd numeric NOT NULL
);


--
-- Name: form_5; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_5 (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    period_of_report date NOT NULL,
    not_subject_to_section16 boolean,
    issuer_cik text NOT NULL,
    issuer_name text NOT NULL,
    issuer_trading_symbol text NOT NULL,
    company_cik text NOT NULL,
    company_name text NOT NULL,
    reporting_owners jsonb NOT NULL,
    person_cik text NOT NULL,
    person_name text NOT NULL,
    is_officer boolean,
    is_director boolean,
    is_ten_pct boolean,
    officer_title text,
    transactions jsonb NOT NULL,
    sale_count bigint NOT NULL,
    total_sale_usd bigint NOT NULL
);


--
-- Name: form_8_k; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_8_k (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    items jsonb,
    item_count bigint,
    body_text_head text NOT NULL
);


--
-- Name: form_c; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_c (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    submission_type text NOT NULL,
    company_name text NOT NULL,
    company_cik text NOT NULL,
    entity_type text,
    jurisdiction_of_inc text,
    date_incorporation text,
    issuer_website text,
    intermediary_name text,
    intermediary_cik text,
    intermediary_crd text,
    progress_update jsonb,
    security_offered_type text,
    price numeric,
    offering_amount numeric,
    target_offering_amount jsonb,
    maximum_offering_amount numeric,
    deadline text,
    current_employees numeric,
    total_asset_most_recent_fy numeric,
    total_revenue_most_recent_fy jsonb,
    net_income_most_recent_fy numeric
);


--
-- Name: form_c_a; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_c_a (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    submission_type text NOT NULL,
    company_name text NOT NULL,
    company_cik text NOT NULL,
    entity_type text,
    jurisdiction_of_inc text,
    date_incorporation text,
    issuer_website text,
    intermediary_name text,
    intermediary_cik text,
    intermediary_crd jsonb,
    progress_update jsonb,
    security_offered_type text,
    price jsonb,
    offering_amount numeric,
    target_offering_amount jsonb,
    maximum_offering_amount numeric,
    deadline text,
    current_employees numeric,
    total_asset_most_recent_fy numeric,
    total_revenue_most_recent_fy jsonb,
    net_income_most_recent_fy numeric
);


--
-- Name: form_d_a; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_d_a (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    entity_name text,
    entity_type text,
    jurisdiction_of_inc text,
    year_of_inc text,
    company_name text,
    submission_type text,
    is_amendment boolean,
    company_cik text,
    industry_group_type text,
    investment_fund_type text,
    revenue_range text,
    aggregate_net_asset_value_range text,
    date_of_first_sale date,
    total_offering_amount bigint,
    total_amount_sold bigint,
    total_remaining bigint,
    minimum_investment_accepted bigint,
    total_number_already_invested bigint,
    has_non_accredited_investors boolean
);


--
-- Name: form_def_14a; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_def_14a (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    body_text_head text NOT NULL,
    document_title text
);


--
-- Name: form_fwp; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_fwp (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    body_text_head text NOT NULL,
    document_title text
);


--
-- Name: form_n_14; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_n_14 (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    body_text_head text NOT NULL,
    document_title jsonb
);


--
-- Name: form_n_cen; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_n_cen (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    holdings jsonb NOT NULL,
    holdings_count bigint,
    total_holding_value_usd bigint
);


--
-- Name: form_n_port; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_n_port (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    series_name text NOT NULL,
    reg_name text NOT NULL,
    reg_cik text NOT NULL,
    company_name text NOT NULL,
    company_cik text NOT NULL,
    rep_pd_end date NOT NULL,
    rep_pd_date date NOT NULL,
    total_assets numeric,
    total_liabilities numeric,
    net_assets numeric,
    holdings jsonb NOT NULL,
    holdings_count bigint,
    total_holding_value_usd numeric
);


--
-- Name: form_n_px; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_n_px (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    holdings jsonb NOT NULL,
    holdings_count bigint,
    total_holding_value_usd bigint
);


--
-- Name: form_s_1; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_s_1 (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    body_text_head text NOT NULL,
    document_title text
);


--
-- Name: form_s_1_a; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_s_1_a (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    body_text_head text NOT NULL,
    document_title text
);


--
-- Name: form_s_3; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_s_3 (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    body_text_head text NOT NULL,
    document_title text
);


--
-- Name: form_sc_13d; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_sc_13d (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    submission_type text,
    securities_class_title text,
    date_of_event jsonb,
    reporting_persons jsonb NOT NULL,
    issuer_cik text,
    issuer_name text,
    company_name text,
    company_cik text,
    cusips jsonb,
    cusip text,
    filer_name text,
    person_name text,
    person_cik text,
    pct_of_class numeric,
    shares_owned bigint,
    max_pct_of_class numeric,
    sum_shares_owned bigint
);


--
-- Name: form_sc_13g; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_sc_13g (
    accession text NOT NULL,
    form_type text NOT NULL,
    filing_date date NOT NULL,
    filer_cik text NOT NULL,
    doc_url text NOT NULL,
    doc_name text NOT NULL,
    doc_mime text NOT NULL,
    index_url text NOT NULL,
    byte_size bigint NOT NULL,
    submission_type text,
    securities_class_title text,
    date_of_event jsonb,
    issuer_cik text,
    issuer_name text,
    company_name text,
    company_cik text,
    cusips jsonb,
    cusip text,
    reporting_persons jsonb NOT NULL
);


--
-- Name: forms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.forms (
    form text NOT NULL,
    purpose text NOT NULL,
    why_filed text NOT NULL,
    nubeam_relevance text NOT NULL,
    signal_side text NOT NULL,
    filings_count bigint DEFAULT 0 NOT NULL,
    companies_count bigint DEFAULT 0 NOT NULL,
    CONSTRAINT forms_signal_side_check CHECK ((signal_side = ANY (ARRAY['allocator'::text, 'seeker'::text, 'unknown'::text])))
);


--
-- Name: people; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.people (
    person_cik text NOT NULL,
    canonical_name text NOT NULL,
    former_names jsonb NOT NULL,
    address text,
    entity_type text NOT NULL,
    date_added timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: people_filings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.people_filings (
    person_cik text NOT NULL,
    accession text NOT NULL,
    form text NOT NULL,
    filing_date date NOT NULL,
    date_added timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: signal_ciks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.signal_ciks (
    accession text NOT NULL,
    cik text NOT NULL,
    cik_role text NOT NULL
);


--
-- Name: signals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.signals (
    accession text NOT NULL,
    form_type text NOT NULL,
    date_added timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: cik_list cik_list_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cik_list
    ADD CONSTRAINT cik_list_pkey PRIMARY KEY (cik);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (company_cik);


--
-- Name: company_filings company_filings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_filings
    ADD CONSTRAINT company_filings_pkey PRIMARY KEY (company_cik, accession);


--
-- Name: form_10_q form_10_q_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_10_q
    ADD CONSTRAINT form_10_q_pkey PRIMARY KEY (accession);


--
-- Name: form_13f_hr form_13f_hr_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_13f_hr
    ADD CONSTRAINT form_13f_hr_pkey PRIMARY KEY (accession);


--
-- Name: form_13f_nt form_13f_nt_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_13f_nt
    ADD CONSTRAINT form_13f_nt_pkey PRIMARY KEY (accession);


--
-- Name: form_144_a form_144_a_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_144_a
    ADD CONSTRAINT form_144_a_pkey PRIMARY KEY (accession);


--
-- Name: form_144 form_144_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_144
    ADD CONSTRAINT form_144_pkey PRIMARY KEY (accession);


--
-- Name: form_3 form_3_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_3
    ADD CONSTRAINT form_3_pkey PRIMARY KEY (accession);


--
-- Name: form_40_app form_40_app_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_40_app
    ADD CONSTRAINT form_40_app_pkey PRIMARY KEY (accession);


--
-- Name: form_424b5 form_424b5_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_424b5
    ADD CONSTRAINT form_424b5_pkey PRIMARY KEY (accession);


--
-- Name: form_425 form_425_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_425
    ADD CONSTRAINT form_425_pkey PRIMARY KEY (accession);


--
-- Name: form_4_a form_4_a_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_4_a
    ADD CONSTRAINT form_4_a_pkey PRIMARY KEY (accession);


--
-- Name: form_4 form_4_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_4
    ADD CONSTRAINT form_4_pkey PRIMARY KEY (accession);


--
-- Name: form_5 form_5_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_5
    ADD CONSTRAINT form_5_pkey PRIMARY KEY (accession);


--
-- Name: form_8_k form_8_k_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_8_k
    ADD CONSTRAINT form_8_k_pkey PRIMARY KEY (accession);


--
-- Name: form_c_a form_c_a_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_c_a
    ADD CONSTRAINT form_c_a_pkey PRIMARY KEY (accession);


--
-- Name: form_c form_c_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_c
    ADD CONSTRAINT form_c_pkey PRIMARY KEY (accession);


--
-- Name: form_d_a form_d_a_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_d_a
    ADD CONSTRAINT form_d_a_pkey PRIMARY KEY (accession);


--
-- Name: form_def_14a form_def_14a_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_def_14a
    ADD CONSTRAINT form_def_14a_pkey PRIMARY KEY (accession);


--
-- Name: form_fwp form_fwp_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_fwp
    ADD CONSTRAINT form_fwp_pkey PRIMARY KEY (accession);


--
-- Name: form_n_14 form_n_14_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_n_14
    ADD CONSTRAINT form_n_14_pkey PRIMARY KEY (accession);


--
-- Name: form_n_cen form_n_cen_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_n_cen
    ADD CONSTRAINT form_n_cen_pkey PRIMARY KEY (accession);


--
-- Name: form_n_port form_n_port_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_n_port
    ADD CONSTRAINT form_n_port_pkey PRIMARY KEY (accession);


--
-- Name: form_n_px form_n_px_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_n_px
    ADD CONSTRAINT form_n_px_pkey PRIMARY KEY (accession);


--
-- Name: form_s_1_a form_s_1_a_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_s_1_a
    ADD CONSTRAINT form_s_1_a_pkey PRIMARY KEY (accession);


--
-- Name: form_s_1 form_s_1_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_s_1
    ADD CONSTRAINT form_s_1_pkey PRIMARY KEY (accession);


--
-- Name: form_s_3 form_s_3_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_s_3
    ADD CONSTRAINT form_s_3_pkey PRIMARY KEY (accession);


--
-- Name: form_sc_13d form_sc_13d_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_sc_13d
    ADD CONSTRAINT form_sc_13d_pkey PRIMARY KEY (accession);


--
-- Name: form_sc_13g form_sc_13g_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_sc_13g
    ADD CONSTRAINT form_sc_13g_pkey PRIMARY KEY (accession);


--
-- Name: forms forms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forms
    ADD CONSTRAINT forms_pkey PRIMARY KEY (form);


--
-- Name: people_filings people_filings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people_filings
    ADD CONSTRAINT people_filings_pkey PRIMARY KEY (person_cik, accession);


--
-- Name: people people_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people
    ADD CONSTRAINT people_pkey PRIMARY KEY (person_cik);


--
-- Name: signal_ciks signal_ciks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signal_ciks
    ADD CONSTRAINT signal_ciks_pkey PRIMARY KEY (accession, cik, cik_role);


--
-- Name: signals signals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signals
    ADD CONSTRAINT signals_pkey PRIMARY KEY (accession);


--
-- Name: idx_company_filings_filing_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_filings_filing_date ON public.company_filings USING btree (filing_date);


--
-- Name: idx_company_filings_form; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_filings_form ON public.company_filings USING btree (form);


--
-- Name: idx_people_filings_filing_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_people_filings_filing_date ON public.people_filings USING btree (filing_date);


--
-- Name: idx_people_filings_form; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_people_filings_form ON public.people_filings USING btree (form);


--
-- Name: idx_signal_ciks_accession; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_signal_ciks_accession ON public.signal_ciks USING btree (accession);


--
-- Name: idx_signal_ciks_cik; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_signal_ciks_cik ON public.signal_ciks USING btree (cik);


--
-- Name: idx_signals_form_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_signals_form_date ON public.signals USING btree (form_type, date_added);


--
-- Name: companies companies_company_cik_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_company_cik_fkey FOREIGN KEY (company_cik) REFERENCES public.cik_list(cik) ON DELETE CASCADE;


--
-- Name: company_filings company_filings_company_cik_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_filings
    ADD CONSTRAINT company_filings_company_cik_fkey FOREIGN KEY (company_cik) REFERENCES public.companies(company_cik) ON DELETE CASCADE;


--
-- Name: signals fk_signals_form_type; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signals
    ADD CONSTRAINT fk_signals_form_type FOREIGN KEY (form_type) REFERENCES public.forms(form) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: form_10_q form_10_q_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_10_q
    ADD CONSTRAINT form_10_q_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_13f_hr form_13f_hr_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_13f_hr
    ADD CONSTRAINT form_13f_hr_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_13f_nt form_13f_nt_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_13f_nt
    ADD CONSTRAINT form_13f_nt_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_144_a form_144_a_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_144_a
    ADD CONSTRAINT form_144_a_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_144 form_144_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_144
    ADD CONSTRAINT form_144_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_3 form_3_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_3
    ADD CONSTRAINT form_3_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_40_app form_40_app_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_40_app
    ADD CONSTRAINT form_40_app_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_424b5 form_424b5_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_424b5
    ADD CONSTRAINT form_424b5_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_425 form_425_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_425
    ADD CONSTRAINT form_425_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_4_a form_4_a_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_4_a
    ADD CONSTRAINT form_4_a_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_4 form_4_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_4
    ADD CONSTRAINT form_4_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_5 form_5_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_5
    ADD CONSTRAINT form_5_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_8_k form_8_k_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_8_k
    ADD CONSTRAINT form_8_k_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_c_a form_c_a_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_c_a
    ADD CONSTRAINT form_c_a_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_c form_c_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_c
    ADD CONSTRAINT form_c_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_d_a form_d_a_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_d_a
    ADD CONSTRAINT form_d_a_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_def_14a form_def_14a_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_def_14a
    ADD CONSTRAINT form_def_14a_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_fwp form_fwp_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_fwp
    ADD CONSTRAINT form_fwp_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_n_14 form_n_14_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_n_14
    ADD CONSTRAINT form_n_14_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_n_cen form_n_cen_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_n_cen
    ADD CONSTRAINT form_n_cen_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_n_port form_n_port_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_n_port
    ADD CONSTRAINT form_n_port_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_n_px form_n_px_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_n_px
    ADD CONSTRAINT form_n_px_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_s_1_a form_s_1_a_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_s_1_a
    ADD CONSTRAINT form_s_1_a_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_s_1 form_s_1_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_s_1
    ADD CONSTRAINT form_s_1_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_s_3 form_s_3_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_s_3
    ADD CONSTRAINT form_s_3_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_sc_13d form_sc_13d_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_sc_13d
    ADD CONSTRAINT form_sc_13d_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: form_sc_13g form_sc_13g_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_sc_13g
    ADD CONSTRAINT form_sc_13g_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: people_filings people_filings_person_cik_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people_filings
    ADD CONSTRAINT people_filings_person_cik_fkey FOREIGN KEY (person_cik) REFERENCES public.people(person_cik) ON DELETE CASCADE;


--
-- Name: people people_person_cik_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.people
    ADD CONSTRAINT people_person_cik_fkey FOREIGN KEY (person_cik) REFERENCES public.cik_list(cik) ON DELETE CASCADE;


--
-- Name: signal_ciks signal_ciks_accession_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signal_ciks
    ADD CONSTRAINT signal_ciks_accession_fkey FOREIGN KEY (accession) REFERENCES public.signals(accession) ON DELETE CASCADE;


--
-- Name: signal_ciks signal_ciks_cik_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.signal_ciks
    ADD CONSTRAINT signal_ciks_cik_fkey FOREIGN KEY (cik) REFERENCES public.cik_list(cik) ON DELETE CASCADE;


--
-- Name: cik_list; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cik_list ENABLE ROW LEVEL SECURITY;

--
-- Name: companies; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;

--
-- Name: company_filings; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.company_filings ENABLE ROW LEVEL SECURITY;

--
-- Name: form_10_q; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_10_q ENABLE ROW LEVEL SECURITY;

--
-- Name: form_13f_hr; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_13f_hr ENABLE ROW LEVEL SECURITY;

--
-- Name: form_13f_nt; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_13f_nt ENABLE ROW LEVEL SECURITY;

--
-- Name: form_144; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_144 ENABLE ROW LEVEL SECURITY;

--
-- Name: form_144_a; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_144_a ENABLE ROW LEVEL SECURITY;

--
-- Name: form_3; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_3 ENABLE ROW LEVEL SECURITY;

--
-- Name: form_4; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_4 ENABLE ROW LEVEL SECURITY;

--
-- Name: form_40_app; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_40_app ENABLE ROW LEVEL SECURITY;

--
-- Name: form_424b5; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_424b5 ENABLE ROW LEVEL SECURITY;

--
-- Name: form_425; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_425 ENABLE ROW LEVEL SECURITY;

--
-- Name: form_4_a; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_4_a ENABLE ROW LEVEL SECURITY;

--
-- Name: form_5; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_5 ENABLE ROW LEVEL SECURITY;

--
-- Name: form_8_k; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_8_k ENABLE ROW LEVEL SECURITY;

--
-- Name: form_c; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_c ENABLE ROW LEVEL SECURITY;

--
-- Name: form_c_a; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_c_a ENABLE ROW LEVEL SECURITY;

--
-- Name: form_d_a; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_d_a ENABLE ROW LEVEL SECURITY;

--
-- Name: form_def_14a; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_def_14a ENABLE ROW LEVEL SECURITY;

--
-- Name: form_fwp; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_fwp ENABLE ROW LEVEL SECURITY;

--
-- Name: form_n_14; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_n_14 ENABLE ROW LEVEL SECURITY;

--
-- Name: form_n_cen; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_n_cen ENABLE ROW LEVEL SECURITY;

--
-- Name: form_n_port; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_n_port ENABLE ROW LEVEL SECURITY;

--
-- Name: form_n_px; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_n_px ENABLE ROW LEVEL SECURITY;

--
-- Name: form_s_1; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_s_1 ENABLE ROW LEVEL SECURITY;

--
-- Name: form_s_1_a; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_s_1_a ENABLE ROW LEVEL SECURITY;

--
-- Name: form_s_3; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_s_3 ENABLE ROW LEVEL SECURITY;

--
-- Name: form_sc_13d; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_sc_13d ENABLE ROW LEVEL SECURITY;

--
-- Name: form_sc_13g; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.form_sc_13g ENABLE ROW LEVEL SECURITY;

--
-- Name: forms; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.forms ENABLE ROW LEVEL SECURITY;

--
-- Name: forms forms_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY forms_read ON public.forms FOR SELECT TO anon, authenticated USING (true);


--
-- Name: people; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.people ENABLE ROW LEVEL SECURITY;

--
-- Name: people_filings; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.people_filings ENABLE ROW LEVEL SECURITY;

--
-- Name: signal_ciks; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.signal_ciks ENABLE ROW LEVEL SECURITY;

--
-- Name: signals; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.signals ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict cWBmGdN6dzAZMmoGX8TFCqR9sCfZXL7ICILT7hlpKS93HKT1CkisHFWTKwe71i2

